### ISSUE TITLE
Ordering of tasks suggestion

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/activerecord-costume-store-todo#27]
User: Artem Eremin

Batch: 000

Current Lesson: ActiveRecord ORM Tutorial

Location: https://learn.co/tracks/web-development-with-ruby-on-rails/object-relational-mappers-orms/activerecord-migrations-and-crud/activerecord-costume-store?track_id=5309&batch_id=76

Bug Description: A little bit of mess here. First you make a CreateCandies migration class, which creates :products table, and then you make CostumeStore model, and after that you create Candy instances.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by jmburges** [comment]
This was fixed with commit 110de73733ce30ea249d8fe8931bc6277fe53628
