### ISSUE TITLE
pull request is not getting remote build to pass

### ISSUE THREAD

**Issue by georgetoothman** [learn-co-curriculum/activerecord-costume-store-todo#35]
I forked the old lab which was activerecord-costume-store-todo-0715
then that was changed/updated and i forked and worked on this one.

**Comment by AnnJohn** [comment]
@kvignali Can your team take a look at this. Will check in at the end of the week.

**Comment by kvignali** [comment]
hey @georgetoothman it looks like you opened a pr on the learn co curriculum repo, and not the learn co students repo. Can you open your pr here: https://github.com/learn-co-students/activerecord-costume-store-todo-web-0715

**Comment by georgetoothman** [comment]
wowza good call. ok, all done! thank you : )

**Comment by kvignali** [comment]
great!
