### ISSUE TITLE
"Unitialized constatnt ConnectionAdapter (NameError)"

### ISSUE THREAD

**Issue by bacitracin** [learn-co-curriculum/activerecord-costume-store-todo#38]
Ran bundle & then learn, getting a Name error for the ConnectionAdapter. This also happened with the previous Lab - Writing Migrations, so maybe it's the same issue. 

➜  activerecord-costume-store-todo-001 git:(master) ✗ learn
/home/nitrous/code/labs/activerecord-costume-store-todo-001/lib/support/db_registry.rb:1:in `<top (required)>': uninitialized constant ConnectionAdapter (NameError
)
        from /home/nitrous/code/labs/activerecord-costume-store-todo-001/config/environment.rb:13:in `require'
        from /home/nitrous/code/labs/activerecord-costume-store-todo-001/config/environment.rb:13:in `block in <top (required)>'
        from /home/nitrous/code/labs/activerecord-costume-store-todo-001/config/environment.rb:13:in `each'
        from /home/nitrous/code/labs/activerecord-costume-store-todo-001/config/environment.rb:13:in `<top (required)>'
        from /home/nitrous/code/labs/activerecord-costume-store-todo-001/spec/spec_helper.rb:3:in `require_relative'
        from /home/nitrous/code/labs/activerecord-costume-store-todo-001/spec/spec_helper.rb:3:in `<top (required)>'
        from /home/nitrous/code/labs/activerecord-costume-store-todo-001/.bundle/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `require'
        from /home/nitrous/code/labs/activerecord-costume-store-todo-001/.bundle/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `block in requires='

**Comment by AnnJohn** [comment]
Hi @bacitracin thanks for raising this issue, and yes, we know that there are issues with this and the previous lab. We're looking into it!

**Comment by jmburges** [comment]
fixed!
