### ISSUE TITLE
Ruby activerecord-costume-store-todo lab works with Rspec but doesn't run locally with Ironboard

### ISSUE THREAD

**Issue by changamanda** [learn-co-curriculum/activerecord-costume-store-todo#4]
From Logan: this is an issue with how rake is used in the lab. what's happening is that in https://github.com/flatiron-school-curriculum/activerecord-costume-store-todo/blob/master/config/environment.rb rake is being initialized. and rake is greedy, and steals command line arguments. so this lab will need to be re-written so that rake doesn't get so heavily involved in the environment.rb file.

Error:
invalid option: --format
/Users/villevesterinen/.rvm/gems/ruby-2.2.0/gems/ironboard-0.0.2/lib/ironboard/rspec/runner.rb:64:in read': No such file or directory @ rb_sysopen - .results.json (Errno::ENOENT)

**Comment by AnnJohn** [comment]
Issue fixed in a later pull request. Closing.
