### ISSUE TITLE
Order of labs

### ISSUE THREAD

**Issue by Richard-Frost** [learn-co-curriculum/activerecord-costume-store-todo#40]
Hello, I'm not sure if this is where I am supposed to mention this or if I am correct but it seems like this Lab should be before ActiveRecords CRUD lab.  I was stuck on that lab a long time until looking ahead and seeing this lab had a lot of the info I needed.

**Comment by gooryalhamed** [comment]
Yes you are right.  I have the same opinion.

**Comment by DanMohseni** [comment]
+1
order of labs is what brought me here - I was thinking of suggesting the same.

**Comment by gj** [comment]
Flipped the two labs. Thanks @Richard-Frost !
