### ISSUE TITLE
Common Rake Tasks Not Available

### ISSUE THREAD

**Issue by leighsn** [learn-co-curriculum/activerecord-costume-store-todo#42]
The Rakefile only includes the task rake db:migrate, which is written to drop all the db tables before running migration. I'd suggest adding the sinatra-activerecord gem instead of regular active record so that students will have access to other common rake tasks like rollback, reset, drop, console, etc @AnnJohn

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by gj** [comment]
Fixed. Thanks @leighsn !

**Comment by gj** [comment]
Reopening until we have a better solution. Sorry for the whiplash!

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#61.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
