### ISSUE TITLE
Rake is stealing options

### ISSUE THREAD

**Issue by StevenNunez** [learn-co-curriculum/activerecord-costume-store-todo#5]
There's an issue with labs that Initialize Rake as part of the boot process. It causes rake to start listening for command line flags. Students get errors like `--fail-fast is an invalid option` when running rspec, and learn breaks too since the option to return the results as json gets read by Rake.

**Comment by loganhasson** [comment]
@StevenNunez @jmburges ping. let's get this fixed, as students are submitting bug reports about it and it makes both the learn gem and the remote build fail

**Comment by jmburges** [comment]
on it

**Comment by jmburges** [comment]
@roseweixel is looking into this

**Comment by AnnJohn** [comment]
Issue fixed in a later PR and merge. Closing issue.
