### ISSUE TITLE
DB Problems when using db:migrate and making mistakes

### ISSUE THREAD

**Issue by survivingknowledge** [learn-co-curriculum/activerecord-costume-store-todo#51]
I first wrote out the migrations but in haunted_houses i forgot to include the family_friendly booleans and forgot to add t.timestamps to costumes. I did db:rollback to undo the changes then db:migrate to redo it with the new changes. However when running learn, the same 3 errors where still there saying i didn't have timestamps and no family_friendly boolean. No matter how many times i db:rollback it didn't change the db, least to its original starting point. I only got it working by deleting the halloween-<>.db files then running learn again which is finally created the correct db. I know that in the real world , deleteing your db wouln't be a solution, so how would you fix it, unless you do more migration files to make more changes?

**Comment by gj** [comment]
>so how would you fix it, unless **you do more migration files to make more changes**?

Bingo. 🙂
