### ISSUE TITLE
Rails version

### ISSUE THREAD

**Issue by Apex-Code** [learn-co-curriculum/activerecord-costume-store-todo#53]
Maybe add something in the readme, or in prior classes something about the Rails version error that throws if not added to the end of the migrate.  Example of error:

`Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:         `

While I understand that some detective work will reveal the answer:

`class CreateCostumeStores < ActiveRecord::Migration**[4.2]**
`

However, I don't remember this from prior lessons, and being that I have yet to reach Rails...  

Respectfully,

Dave

**Comment by kwebster2** [comment]
@aturkewi @cjbrock 
This issue still persists. The pre-written migrations were written for an older version of Rails, though the IDE and a lot of students are now using Rails 5.0 or above, so the migrations do not work.

**Comment by kwebster2** [comment]
@aturkewi @cjbrock 
This issue still persists. Since the IDE, as well as a lot of students locally, use Rails 5, the directions given to write a migration do not work, since Rails 5 requires the Rails version to be specified when inheriting from ActiveRecord::Migration.

**Comment by cjbrock** [comment]
Tagging @cernanb in this one as he covers the ORM section.
