### ISSUE TITLE
Weird bug when running learn --f-f

### ISSUE THREAD

**Issue by CodeDad70** [learn-co-curriculum/activerecord-costume-store-todo#55]
Every time I would run the spec on this it would fail the first time - if I ran it again it would pass the second time without me changing anything ! Very bizarre - example code below - not I did not change my migration code between the 2 times I ran this text :

'''♥ learn --f-f
== 1 CreateCostumes: migrating ================================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:costumes, {:id=>:integer})
   -> 0.0013s
== 1 CreateCostumes: migrated (0.0015s) =======================================

== 2 CreateCostumeStores: migrating ===========================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:costume_stores, {:id=>:integer})
   -> 0.0016s
== 2 CreateCostumeStores: migrated (0.0019s) ==================================

== 3 CreateHauntedHouses: migrating ===========================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:haunted_houses, {:id=>:integer})
   -> 0.0010s
== 3 CreateHauntedHouses: migrated (0.0012s) ==================================

Costume
  has a name
  has a price
  has an image url
  has a size
  knows when it was created
  knows when it was last updated

CostumeStore
  has a name
  has a location
  has a costume inventory
  has an employees count
  knows if it's still in business or permanently closed
  has an opening time
  has a closing time

HauntedHouse
  has a name
  has a location
  has a theme
  has a price
  knows if it's family friendly
  has an opening date
  has a closing date (FAILED - 1)

Failures:

  1) HauntedHouse has a closing date
     Failure/Error: esp = HauntedHouse.create(name: "Eastern State Penitentiary", closing_date: nov_2nd)
     
     ActiveModel::UnknownAttributeError:
       unknown attribute 'closing_date' for HauntedHouse.
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activemodel-5.1.3/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activemodel-5.1.3/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activemodel-5.1.3/lib/active_model/attribute_assignment.rb:39:in `each'
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activemodel-5.1.3/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.3/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activemodel-5.1.3/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.3/lib/active_record/core.rb:337:in `initialize'
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.3/lib/active_record/inheritance.rb:66:in `new'
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.3/lib/active_record/inheritance.rb:66:in `new'
     # /Users/TeamCaric/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.3/lib/active_record/persistence.rb:33:in `create'
     # ./spec/haunted_house_spec.rb:53:in `block (2 levels) in <top (required)>'

Finished in 2.09 seconds (files took 0.88937 seconds to load)
20 examples, 1 failure

Failed examples:

rspec ./spec/haunted_house_spec.rb:51 # HauntedHouse has a closing date

[21:48:58] (master) activerecord-costume-store-todo-v-000
// ♥ learn --f-f
== 1 CreateCostumes: migrating ================================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:costumes, {:id=>:integer})
   -> 0.0019s
== 1 CreateCostumes: migrated (0.0021s) =======================================

== 2 CreateCostumeStores: migrating ===========================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:costume_stores, {:id=>:integer})
   -> 0.0008s
== 2 CreateCostumeStores: migrated (0.0010s) ==================================

== 3 CreateHauntedHouses: migrating ===========================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:haunted_houses, {:id=>:integer})
   -> 0.0009s
== 3 CreateHauntedHouses: migrated (0.0010s) ==================================

Costume
  has a name
  has a price
  has an image url
  has a size
  knows when it was created
  knows when it was last updated

CostumeStore
  has a name
  has a location
  has a costume inventory
  has an employees count
  knows if it's still in business or permanently closed
  has an opening time
  has a closing time

HauntedHouse
  has a name
  has a location
  has a theme
  has a price
  knows if it's family friendly
  has an opening date
  has a closing date
  has a long, long description (FAILED - 1)'''

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
