### ISSUE TITLE
rake console doesn't work

### ISSUE THREAD

**Issue by dsbondin** [learn-co-curriculum/activerecord-costume-store-todo#58]
```
task :console => :environment do
  Pry.start
end
```
rake console calls for Pry but it wasn't requested by the Gemfile and environment.rb

Need to add:
#Gemfile
`gem "pry"`

#environment.rb
`require 'pry'`

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We added the 'pry' dependency.

As always thank you for contributing.
