### ISSUE TITLE
Active Record 5.x

### ISSUE THREAD

**Issue by Ssenkowski** [learn-co-curriculum/activerecord-costume-store-todo#59]
## Hi just thought it might be helpful to mention this note a section earlier in the _Writing Our Own Migrations_ lab. 

> NOTE: As of Active Record 5.x, we can no longer inherit directly from ActiveRecord::Migration and must instead specify which version of Active Record / Rails the migration was written for. If we were writing a migration for Active Record 5.1, we would inherit from ActiveRecord::Migration[5.1]. Don't worry too much about this until you get to the Rails section. Until then, if you encounter an error like this...
> StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
>  
>   class CreateDogs < ActiveRecord::Migration[4.2]
> ...simply add [4.2] to the end of ActiveRecord::Migration, exactly as the error message instructs.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We added the notice to the previous lesson.

As always thank you for contributing!
