### ISSUE TITLE
rake db:migrate errors if student has not defined all migrations before running it

### ISSUE THREAD

**Issue by wlycdgrfromflatiron** [learn-co-curriculum/activerecord-costume-store-todo#60]
Students may want to work through the lab incrementally, running db:migrate after implementing each migration class. But, running rake db:migrate after implementing only 001_create_costumes.rb produces a fatal error that aborts the migration: "NameError: uninitialized constant CreateCostumeStores"

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#61.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @wlycdgr,

Thank you for this feedback. This lesson's support files and instructions have been updated so that this so no longer occur.

Thank you for contributing to this lesson!
