### ISSUE TITLE
Change to Gemfile

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/activerecord-costume-store-todo#67]
Hey there, I experienced an issue loading the specs when I started the lesson. The Gemfile needs to be updated to `gem 'sqlite3', '~> 1.3.7'`

Best,
A

**Comment by maxwellbenton** [comment]
Hi @helloamandamurphy,

Thank you for opening this issue. We've updated references to the `sqlite` gem to use `~> 1.3.6`, which resolves this SQLite version conflict.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
