### ISSUE TITLE
Lab no longer runs Rake tasks through test suite

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/activerecord-costume-store-todo#8]
Regarding #4 and #5, I think #7 introduced some new problems. Rake does not seem to be running prior to each rspec pass. I think 780ff93344eec91ffd788b2a7ef406ea726940d4 is the cause. 

To verify confirm findings, if I create my own DB and emulate it be the test DB, everything passes. But the test DB will forever be empty with no rake tasks :(

PS - would it make sense to highlight that Sublime by (our?) default does not show .db files in the file sidebar? Two students have mentioned they find the invisible DB quite mysterious and confusing.

**Comment by AnnJohn** [comment]
iceboxing for now

**Comment by jmburges** [comment]
Let's check into this one to make sure everything works

**Comment by jmburges** [comment]
@sammarcus can you clarify what doesn't work? I'm running on my machine and the tests pass

**Comment by sammarcus** [comment]
@jmburges the original issue was that rake was not running when rspec was run. I believe it should be run automatically prior to it actually testing to see if the answers are correct. but it wasn't running with each rspec test, which would cause obvious failures such as things not being migrated, etc. is that not happening for you now?

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. This issue does not appear to be happing with the latest round of updates.

As always thank you for contributing!
